# Generated by Django 5.2.7 on 2025-10-20 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('matricula_profesional', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('especialistas', models.ManyToManyField(blank=True, related_name='pacientes_asignados', to='salud_osea.especialista')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(max_length=100)),
                ('fecha_examen', models.DateField()),
                ('valor_t_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('angulo_cobb', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('url_documento', models.URLField(blank=True, max_length=255, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='salud_osea.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_enfermedad', models.CharField(max_length=50)),
                ('nivel_gravedad', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_diagnostico', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='salud_osea.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_terapia', models.CharField(max_length=100)),
                ('duracion_semanas', models.IntegerField(blank=True, null=True)),
                ('dosis_medicamento', models.CharField(blank=True, max_length=150, null=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='salud_osea.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_control', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('resultado_mejora', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='salud_osea.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud_osea.especialista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud_osea.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'especialista')},
            },
        ),
    ]
