# Generated by Django 5.2.7 on 2025-10-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud_osea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
