# Generated by Django 5.2.9 on 2025-12-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud_osea', '0002_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha_diagnostico',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del Diagnóstico'),
        ),
    ]
